### ISSUE TITLE
Hugging Face Model 14B Chat Model card has a clerical error.

### ISSUE THREAD

**Issue by Ruomoe** [codefuse-ai/CodeFuse-DevOps-Model#3]
**https://huggingface.co/codefuse-ai/CodeFuse-DevOps-Model-14B-Chat** 
![图片](https://github.com/codefuse-ai/CodeFuse-DevOps-Model/assets/16109205/375b9418-d743-4100-9ebe-6c5214514115)

**Comment by bingxuchai** [comment]
Thank you for pointing it out! Fixed
