### ISSUE TITLE
when will you support  fastchat ? 

### ISSUE THREAD

**Issue by dessun888** [codefuse-ai/CodeFuse-DevOps-Model#4]
When do you support fastchat? Currently, there is an API exception when deploying fastchat.

python -m fastchat.serve.vllm_worker --model-names kagentlms_qwen_7b_mat --model-path /data/model/modelscope_hub/qwen/kagentlms_qwen_7b_mat  --dtype half --controller-address http://$IP:21001    --trust-remote-code --enforce-eager 
run ok.
python -m fastchat.serve.vllm_worker --model-names CodeFuse-DevOps-Model-14B-Chat --model-path /data/model/modelscope_hub/codefuse-ai/CodeFuse-DevOps-Model-14B-Chat    --dtype half --controller-address http://$IP:21001 --max-log-len=2000     --trust-remote-code --enforce-eager
run error with lots of prompts unneed .
2024-01-03 16:48:57 | INFO | stdout | INFO:     127.0.0.1:52652 - "POST /worker_generate_stream HTTP/1.1" 200 OK
INFO 01-03 16:48:57 async_llm_engine.py:379] Received request 4df14bc8f28944399134d3e8204757ad: prompt: "A chat between a curious human and an artificial intelligence assistant. The assistant gives helpful, detailed, and polite answers to the human's questions.\n### Human: Got any creative ideas for a 10 year old’s birthday?\n### Assistant: Of course! Here are some creative ideas for a 10-year-old's birthday party:\n1. Treasure Hunt: Organize a treasure hunt in your backyard or nearby park. Create clues and riddles for the kids to solve, leading them to hidden treasures and surprises.\n2. Science Party: Plan a science-themed party where kids can engage in fun and interactive experiments. You can set up different stations with activities like making slime, erupting volcanoes, or creating simple chemical reactions.\n3. Outdoor Movie Night: Set up a backyard movie night with a projector and a large screen or white sheet. Create a cozy seating area with blankets and pillows, and serve popcorn and snacks while the kids enjoy a favorite movie under the stars.\n4. DIY Crafts Party: Arrange a craft party where kids can unleash their creativity. Provide a variety of craft supplies like beads, paints, and fabrics, and let them create their own unique masterpieces to take home as party favors.\n5. Sports Olympics: Host a mini Olympics event with various sports and games. Set up different stations for activities like sack races, relay races, basketball shooting, and obstacle courses. Give out medals or certificates to the participants.\n6. Cooking Party: Have a cooking-themed party where the kids can prepare their own mini pizzas, cupcakes, or cookies. Provide toppings, frosting, and decorating supplies, and let them get hands-on in the kitchen.\n7. Superhero Training Camp: Create a superhero-themed party where the kids can engage in fun training activities. Set up an obstacle course, have them design their own superhero capes or masks, and organize superhero-themed games and challenges.\n8. Outdoor Adventure: Plan an outdoor adventure party at a local park or nature reserve. Arrange activi", sampling params: SamplingParams(n=1, best_of=1, presence_penalty=0.0, frequency_penalty=0.0, repetition_penalty=1.0, temperature=0.7, top_p=1.0, top_k=-1.0, min_p=0.0, use_beam_search=False, length_penalty=1.0, early_stopping=False, stop=['<|im_end|>', '###'], stop_token_ids=[151645], include_stop_str_in_output=False, ignore_eos=False, max_tokens=512, logprobs=None, prompt_logprobs=None, skip_special_tokens=True, spaces_between_special_tokens=True), prompt token ids: None.
WARNING 01-03 16:48:57 scheduler.py:161] Input prompt (456 tokens) is too long and exceeds the capacity of block_manager
INFO 01-03 16:48:57 async_llm_engine.py:111] Finished request 4df14bc8f28944399134d3e8204757ad.
INFO 01-03 16:48:57 async_llm_engine.py:134] Aborted request 4df14bc8f28944399134d3e8204757ad.

conda 环境
python 3.10.13 
相关依赖
accelerate                0.25.0
aiofiles                  23.2.1
aiohttp                   3.9.1
aioprometheus             23.12.0
aiosignal                 1.3.1
altair                    5.2.0
anyio                     4.2.0
async-timeout             4.0.3
attrs                     23.1.0
beautifulsoup4            4.12.2
Brotli                    1.1.0
bs4                       0.0.1
certifi                   2023.11.17
cffi                      1.16.0
charset-normalizer        3.3.2
click                     8.1.7
contourpy                 1.2.0
cryptography              41.0.7
cycler                    0.12.1
docstring-parser          0.15
duckduckgo-search         3.8.4
ephem                     4.1.4
exceptiongroup            1.2.0
fastapi                   0.108.0
ffmpy                     0.3.1
filelock                  3.13.1
fonttools                 4.47.0
frozenlist                1.4.1
fschat                    0.2.34
fsspec                    2023.12.2
gradio                    3.50.2
gradio_client             0.6.1
h11                       0.14.0
h2                        4.1.0
hpack                     4.0.0
httpcore                  1.0.2
httptools                 0.6.1
httpx                     0.26.0
huggingface-hub           0.20.1
hyperframe                6.0.1
idna                      3.6
importlib-resources       6.1.1
Jinja2                    3.1.2
jsonschema                4.20.0
jsonschema-specifications 2023.12.1
kiwisolver                1.4.5
kwaiagents                0.0.1        /data/jupyter_multi_users/dessun/ks_agent/KwaiAgents-main
libretranslatepy          2.1.1
lunar-python              1.3.2
lxml                      4.9.4
markdown-it-py            3.0.0
markdown2                 2.4.12
MarkupSafe                2.1.3
matplotlib                3.8.2
mdurl                     0.1.2
mpmath                    1.3.0
msgpack                   1.0.7
multidict                 6.0.4
networkx                  3.2.1
nh3                       0.2.15
ninja                     1.11.1.1
numpy                     1.26.2
nvidia-cublas-cu12        12.1.3.1
nvidia-cuda-cupti-cu12    12.1.105
nvidia-cuda-nvrtc-cu12    12.1.105
nvidia-cuda-runtime-cu12  12.1.105
nvidia-cudnn-cu12         8.9.2.26
nvidia-cufft-cu12         11.0.2.54
nvidia-curand-cu12        10.3.2.106
nvidia-cusolver-cu12      11.4.5.107
nvidia-cusparse-cu12      12.1.0.106
nvidia-nccl-cu12          2.18.1
nvidia-nvjitlink-cu12     12.3.101
nvidia-nvtx-cu12          12.1.105
openai                    0.27.8
orjson                    3.9.10
outcome                   1.3.0.post0
packaging                 23.2
pandas                    2.1.4
peft                      0.7.1
Pillow                    10.1.0
pip                       23.3.1
prompt-toolkit            3.0.43
protobuf                  4.25.1
psutil                    5.9.7
pyarrow                   14.0.2
pycparser                 2.21
pydantic                  1.10.13
pydub                     0.25.1
Pygments                  2.17.2
pyOpenSSL                 22.0.0
pyparsing                 3.1.1
PySocks                   1.7.1
python-dateutil           2.8.2
python-dotenv             1.0.0
python-multipart          0.0.6
pytz                      2023.3.post1
PyYAML                    6.0.1
quantile-python           1.1
ray                       2.9.0
referencing               0.32.0
regex                     2023.12.25
requests                  2.31.0
rich                      13.7.0
rpds-py                   0.16.2
safetensors               0.4.1
selenium                  4.1.4
semantic-version          2.10.0
sentencepiece             0.1.99
setuptools                68.2.2
shortuuid                 1.0.11
six                       1.16.0
sniffio                   1.3.0
socksio                   1.0.0
sortedcontainers          2.4.0
soupsieve                 2.5
starlette                 0.32.0.post1
svgwrite                  1.4.3
sympy                     1.12
tiktoken                  0.5.2
tokenizers                0.15.0
toolz                     0.12.0
torch                     2.1.2
tqdm                      4.66.1
transformers              4.36.2
translate                 3.6.1
trio                      0.23.2
trio-websocket            0.11.1
triton                    2.1.0
typing_extensions         4.9.0
tzdata                    2023.3
urllib3                   1.26.18
urllib3-secure-extra      0.1.0
uvicorn                   0.25.0
uvloop                    0.19.0
vllm                      0.2.6
watchfiles                0.21.0
wavedrom                  2.0.3.post3
wcwidth                   0.2.12
webdriver-manager         3.8.6
websockets                11.0.3
wheel                     0.41.2
wsproto                   1.2.0
xformers                  0.0.23.post1
yarl                      1.9.4

**Comment by lightislost** [comment]
you can use fastchat to access devops-model from the documentation (https://github.com/codefuse-ai/codefuse-chatbot/blob/main/sources/readme_docs/fastchat.md)
